# Generated by Django 5.1.3 on 2025-03-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_killlog_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='killlog_object',
            name='KillLog_Process_Id',
            field=models.IntegerField(default=1000),
        ),
    ]
