name: Main testing pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  lint:
    name: Lint and Fix 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installig Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
        
      - name: Run linting and fixing
        run: ruff check . --ignore E711,E712,F841 --fix

      - name: Run formatting
        run: ruff format
