name: Main testing pipeline


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: write


jobs:
  lint:
    name: Lint and Fix 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Installig Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
        
      - name: Run linting and fixing
        run: ruff check . --ignore E711,E712,F841,F405,F403 --fix

      - name: Run formatting
        run: ruff format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
  test:
    name: Django test 
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test